#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(CDPATH= cd -- "${SCRIPT_DIR}/../.." && pwd)
BUILD_DIR="${ROOT_DIR}/build/linux"
PCAP_CAPTURE="${APLAY_PCAP_CAPTURE:-${ROOT_DIR}/resources/pcap/mdns_announce.pcapng}"
RESULT_DIR="${APLAY_MDNS_RESULT_DIR:-${ROOT_DIR}/resources/pcap}"
RESULT_FILE="${APLAY_MDNS_RESULT:-${RESULT_DIR}/mdns_verify_result.txt}"
PROGRESS_FILE="${APLAY_MDNS_PROGRESS:-${RESULT_DIR}/mdns_verify_progress.md}"
REPLAY_LOG="${APLAY_MDNS_REPLAY_LOG:-${RESULT_DIR}/mdns_replay.log}"
CAPTURE_IFACE="${APLAY_CAPTURE_IFACE:-any}"
RECEIVER_NAME="APlayHarness"
DEVICE_ID="02:00:00:00:00:01"
HOST_NAME="${RECEIVER_NAME}.local"
ANNOUNCE_BIN="${BUILD_DIR}/scripts/harness/mdns/aplay_harness_mdns_announce"
REPLAY_BIN="${BUILD_DIR}/scripts/harness/mdns/aplay_harness_mdns_replay"
ANNOUNCE_PID=
CAPTURE_PID=
CAPTURE_TOOL=
PREFLIGHT_CAPTURE="${TMPDIR:-/tmp}/aplay-mdns-preflight.pcapng"

phase_order() {
    case "$1" in
        dependencies) echo 1 ;;
        capture-permission) echo 2 ;;
        submodules) echo 3 ;;
        configure-build) echo 4 ;;
        live-capture) echo 5 ;;
        replay-analysis) echo 6 ;;
        *) echo 0 ;;
    esac
}

phase_background() {
    case "$1" in
        dependencies) echo "Linux harness needs build, capture, and timeout tools before it can produce useful evidence." ;;
        capture-permission) echo "Live UDP 5353 capture requires host capture privileges configured outside the repo." ;;
        submodules) echo "Third-party code must be present before configure/build." ;;
        configure-build) echo "Harness binaries must build from the normal Linux entrypoint." ;;
        live-capture) echo "mDNS behavior must be observable on the host network stack." ;;
        replay-analysis) echo "Protocol semantics must be checked inside the mDNS module." ;;
        *) echo "" ;;
    esac
}

phase_goal() {
    case "$1" in
        dependencies) echo "Fail early with a clear dependency message." ;;
        capture-permission) echo "Prove the selected interface can be opened without sudo." ;;
        submodules) echo "Sync and initialize required submodules." ;;
        configure-build) echo "Configure and build receiver plus mDNS harness tools." ;;
        live-capture) echo "Capture live announcement packets generated by the harness announcer." ;;
        replay-analysis) echo "Validate generated responder packets and captured DNS-SD names." ;;
        *) echo "" ;;
    esac
}

phase_validation() {
    case "$1" in
        dependencies) echo "git, cmake, ninja, timeout, and dumpcap or tcpdump are available." ;;
        capture-permission) echo "dumpcap or tcpdump can open APLAY_CAPTURE_IFACE without sudo." ;;
        submodules) echo "scripts/update_submodules.sh exits successfully." ;;
        configure-build) echo "cmake configure and target build succeed with APLAY_BUILD_HARNESS=ON." ;;
        live-capture) echo "resources/pcap/mdns_announce.pcapng exists and is non-empty." ;;
        replay-analysis) echo "aplay_harness_mdns_replay exits with status 0." ;;
        *) echo "" ;;
    esac
}

phase_changes() {
    case "$1" in
        dependencies) echo "Shell orchestration only." ;;
        capture-permission) echo "Shell orchestration only." ;;
        submodules) echo "No source changes during validation." ;;
        configure-build) echo "CMake enables private module harness code with APLAY_MDNS_HARNESS." ;;
        live-capture) echo "Shell orchestration only." ;;
        replay-analysis) echo "Replay executable calls the private mDNS harness validator." ;;
        *) echo "" ;;
    esac
}

write_progress_row() {
    PHASE=$1
    CURRENT=$2
    CURRENT_STATUS=$3
    CURRENT_MESSAGE=$4
    PHASE_ORDER=$(phase_order "${PHASE}")
    CURRENT_ORDER=$(phase_order "${CURRENT}")

    if [ "${PHASE_ORDER}" -lt "${CURRENT_ORDER}" ]; then
        STATUS="DONE"
        PROGRESS=100
        MESSAGE="completed"
    elif [ "${PHASE_ORDER}" -eq "${CURRENT_ORDER}" ]; then
        STATUS="${CURRENT_STATUS}"
        if [ "${CURRENT_STATUS}" = "DONE" ]; then
            PROGRESS=100
        else
            PROGRESS=50
        fi
        MESSAGE="${CURRENT_MESSAGE}"
    else
        STATUS="TODO"
        PROGRESS=0
        MESSAGE="waiting"
    fi

    {
        echo "### ${PHASE}"
        echo
        echo "- status: ${STATUS}"
        echo "- progress: ${PROGRESS}"
        echo "- background: $(phase_background "${PHASE}")"
        echo "- goal: $(phase_goal "${PHASE}")"
        echo "- current: ${MESSAGE}"
        echo "- validation: $(phase_validation "${PHASE}")"
        echo "- changes: $(phase_changes "${PHASE}")"
        echo
    } >>"${PROGRESS_FILE}"
}

write_progress() {
    CURRENT=$1
    CURRENT_STATUS=$2
    CURRENT_MESSAGE=$3
    CURRENT_ORDER=$(phase_order "${CURRENT}")
    if [ "${CURRENT_STATUS}" = "DONE" ]; then
        OVERALL=$((CURRENT_ORDER * 100 / 6))
    else
        OVERALL=$(((CURRENT_ORDER - 1) * 100 / 6))
    fi

    mkdir -p "${RESULT_DIR}"
    {
        echo "# mDNS Harness Progress"
        echo
        echo "- overall_progress: ${OVERALL}"
        echo "- result_file: ${RESULT_FILE}"
        echo "- replay_log: ${REPLAY_LOG}"
        echo "- capture: ${PCAP_CAPTURE}"
        echo
    } >"${PROGRESS_FILE}"

    write_progress_row dependencies "${CURRENT}" "${CURRENT_STATUS}" "${CURRENT_MESSAGE}"
    write_progress_row capture-permission "${CURRENT}" "${CURRENT_STATUS}" "${CURRENT_MESSAGE}"
    write_progress_row submodules "${CURRENT}" "${CURRENT_STATUS}" "${CURRENT_MESSAGE}"
    write_progress_row configure-build "${CURRENT}" "${CURRENT_STATUS}" "${CURRENT_MESSAGE}"
    write_progress_row live-capture "${CURRENT}" "${CURRENT_STATUS}" "${CURRENT_MESSAGE}"
    write_progress_row replay-analysis "${CURRENT}" "${CURRENT_STATUS}" "${CURRENT_MESSAGE}"
}

start_phase() {
    echo "=== $2 ==="
    write_progress "$1" DOING "$2"
}

finish_phase() {
    write_progress "$1" DONE "$2"
}

write_result() {
    STATUS=$1
    PHASE=$2
    MESSAGE=$3

    mkdir -p "${RESULT_DIR}"
    {
        echo "status=${STATUS}"
        echo "phase=${PHASE}"
        echo "capture=${PCAP_CAPTURE}"
        echo "progress=${PROGRESS_FILE}"
        echo "replay_log=${REPLAY_LOG}"
        echo "message=${MESSAGE}"
    } >"${RESULT_FILE}"
}

fail_phase() {
    PHASE=$1
    MESSAGE=$2
    write_progress "${PHASE}" DOING "${MESSAGE}"
    write_result fail "${PHASE}" "${MESSAGE}"
}

cleanup() {
    if [ -n "${ANNOUNCE_PID}" ]; then
        kill "${ANNOUNCE_PID}" 2>/dev/null || true
        wait "${ANNOUNCE_PID}" 2>/dev/null || true
    fi
    if [ -n "${CAPTURE_PID}" ]; then
        kill "${CAPTURE_PID}" 2>/dev/null || true
        wait "${CAPTURE_PID}" 2>/dev/null || true
    fi
}

trap cleanup EXIT INT TERM

capture_setup_error() {
    PHASE=${1:-capture-permission}
    fail_phase "${PHASE}" "failed to start live mDNS capture without unprivileged packet capture"
    cat >&2 <<EOF
failed to start live mDNS capture without unprivileged packet capture

Configure capture privileges once outside the harness:

Debian/Ubuntu:
  sudo apt-get install wireshark-common
  sudo dpkg-reconfigure wireshark-common
  sudo usermod -aG wireshark "${USER:-${LOGNAME:-current-user}}"
  # start a new login session after changing groups

Capability-based alternative:
  sudo setcap cap_net_raw,cap_net_admin=eip "\$(command -v dumpcap)"
  # or:
  sudo setcap cap_net_raw,cap_net_admin=eip "\$(command -v tcpdump)"
EOF
    exit 1
}

dependency_setup_error() {
    fail_phase dependencies "missing dependencies for Linux harness validation"
    cat >&2 <<EOF
missing dependencies for Linux harness validation

Required commands: git, cmake, ninja, timeout, and either dumpcap or tcpdump.

Debian/Ubuntu setup:
  sudo apt-get install git cmake ninja-build tcpdump wireshark-common
  sudo dpkg-reconfigure wireshark-common
  sudo usermod -aG wireshark "${USER:-${LOGNAME:-current-user}}"
  # start a new login session after changing groups
EOF
    exit 1
}

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "missing required command: $1" >&2
        return 1
    fi
}

check_dependencies() {
    MISSING=0
    require_command git || MISSING=1
    require_command cmake || MISSING=1
    require_command ninja || MISSING=1
    require_command timeout || MISSING=1

    if ! command -v dumpcap >/dev/null 2>&1 && ! command -v tcpdump >/dev/null 2>&1; then
        echo "missing required command: dumpcap or tcpdump" >&2
        MISSING=1
    fi

    if [ "${MISSING}" -ne 0 ]; then
        dependency_setup_error
    fi
}

try_dumpcap_capture() {
    OUTPUT_FILE=$1

    if ! command -v dumpcap >/dev/null 2>&1; then
        return 1
    fi

    timeout 15 dumpcap -i "${CAPTURE_IFACE}" -p -f "udp port 5353" -c 3 \
        -w "${OUTPUT_FILE}" &
    CAPTURE_PID=$!
    sleep 1
    if kill -0 "${CAPTURE_PID}" 2>/dev/null; then
        CAPTURE_TOOL=dumpcap
        return 0
    fi

    wait "${CAPTURE_PID}" 2>/dev/null || true
    CAPTURE_PID=
    rm -f "${OUTPUT_FILE}"
    return 1
}

probe_dumpcap_capture() {
    if ! command -v dumpcap >/dev/null 2>&1; then
        return 1
    fi

    timeout 15 dumpcap -i "${CAPTURE_IFACE}" -p -f "udp port 5353" \
        -w "${PREFLIGHT_CAPTURE}" &
    CAPTURE_PID=$!
    sleep 1
    if ! kill -0 "${CAPTURE_PID}" 2>/dev/null; then
        wait "${CAPTURE_PID}" 2>/dev/null || true
        CAPTURE_PID=
        rm -f "${PREFLIGHT_CAPTURE}"
        return 1
    fi

    CAPTURE_TOOL=dumpcap
    kill "${CAPTURE_PID}" 2>/dev/null || true
    wait "${CAPTURE_PID}" 2>/dev/null || true
    CAPTURE_PID=
    return 0
}

try_tcpdump_capture() {
    OUTPUT_FILE=$1

    if ! command -v tcpdump >/dev/null 2>&1; then
        return 1
    fi

    timeout 15 tcpdump -i "${CAPTURE_IFACE}" -p -n -U -s 0 -c 3 "udp port 5353" \
        -w - >"${OUTPUT_FILE}" &
    CAPTURE_PID=$!
    sleep 1
    if kill -0 "${CAPTURE_PID}" 2>/dev/null; then
        CAPTURE_TOOL=tcpdump
        return 0
    fi

    wait "${CAPTURE_PID}" 2>/dev/null || true
    CAPTURE_PID=
    rm -f "${OUTPUT_FILE}"
    return 1
}

probe_tcpdump_capture() {
    if ! command -v tcpdump >/dev/null 2>&1; then
        return 1
    fi

    timeout 15 tcpdump -i "${CAPTURE_IFACE}" -p -n -U -s 0 "udp port 5353" \
        -w - >"${PREFLIGHT_CAPTURE}" &
    CAPTURE_PID=$!
    sleep 1
    if ! kill -0 "${CAPTURE_PID}" 2>/dev/null; then
        wait "${CAPTURE_PID}" 2>/dev/null || true
        CAPTURE_PID=
        rm -f "${PREFLIGHT_CAPTURE}"
        return 1
    fi

    CAPTURE_TOOL=tcpdump
    kill "${CAPTURE_PID}" 2>/dev/null || true
    wait "${CAPTURE_PID}" 2>/dev/null || true
    CAPTURE_PID=
    return 0
}

check_capture_permissions() {
    rm -f "${PREFLIGHT_CAPTURE}"
    probe_dumpcap_capture || probe_tcpdump_capture || capture_setup_error capture-permission
    rm -f "${PREFLIGHT_CAPTURE}"
    echo "using ${CAPTURE_TOOL} for live mDNS capture"
}

start_capture() {
    if [ "${CAPTURE_TOOL}" = "dumpcap" ]; then
        try_dumpcap_capture "${PCAP_CAPTURE}"
    elif [ "${CAPTURE_TOOL}" = "tcpdump" ]; then
        try_tcpdump_capture "${PCAP_CAPTURE}"
    else
        return 1
    fi
}

mkdir -p "${RESULT_DIR}"
rm -f "${RESULT_FILE}" "${PROGRESS_FILE}" "${REPLAY_LOG}"

start_phase dependencies "Checking Linux harness dependencies"
check_dependencies
finish_phase dependencies "dependencies available"

start_phase capture-permission "Checking live capture permissions"
check_capture_permissions
finish_phase capture-permission "capture permission available through ${CAPTURE_TOOL}"

start_phase submodules "Updating submodules"
sh "${ROOT_DIR}/scripts/update_submodules.sh" "${ROOT_DIR}" || {
    fail_phase submodules "submodule update failed"
    exit 1
}
finish_phase submodules "submodules ready"

start_phase configure-build "Configuring and building Linux harness targets"
cmake -S "${ROOT_DIR}/app/linux" -B "${BUILD_DIR}" -G Ninja \
    -DAPLAY_BUILD_LINUX=ON \
    -DAPLAY_BUILD_HARNESS=ON || {
    fail_phase configure-build "cmake configure failed"
    exit 1
}
cmake --build "${BUILD_DIR}" --target \
    APlayReceiver \
    aplay_harness_mdns_replay \
    aplay_harness_mdns_announce || {
    fail_phase configure-build "cmake build failed"
    exit 1
}
finish_phase configure-build "Linux harness targets built"

mkdir -p "$(dirname -- "${PCAP_CAPTURE}")"
rm -f "${PCAP_CAPTURE}"

start_phase live-capture "Capturing live mDNS announcements"
start_capture || {
    fail_phase live-capture "failed to start live mDNS capture"
    capture_setup_error live-capture
}

"${ANNOUNCE_BIN}" --interval-ms 250 "${RECEIVER_NAME}" &
ANNOUNCE_PID=$!

set +e
wait "${CAPTURE_PID}"
CAPTURE_STATUS=$?
CAPTURE_PID=
set -e

kill "${ANNOUNCE_PID}" 2>/dev/null || true
wait "${ANNOUNCE_PID}" 2>/dev/null || true
ANNOUNCE_PID=

if [ "${CAPTURE_STATUS}" -ne 0 ]; then
    fail_phase live-capture "failed to capture live mDNS announcements"
    echo "failed to capture live mDNS announcements into ${PCAP_CAPTURE}" >&2
    exit "${CAPTURE_STATUS}"
fi

if [ ! -s "${PCAP_CAPTURE}" ]; then
    fail_phase live-capture "captured pcap is missing or empty"
    echo "captured pcap is missing or empty: ${PCAP_CAPTURE}" >&2
    exit 1
fi
finish_phase live-capture "captured live mDNS pcap"

start_phase replay-analysis "Analyzing captured mDNS pcap"
set +e
"${REPLAY_BIN}" "${PCAP_CAPTURE}" "${RECEIVER_NAME}" "${DEVICE_ID}" "${HOST_NAME}" \
    >"${REPLAY_LOG}" 2>&1
REPLAY_STATUS=$?
set -e
cat "${REPLAY_LOG}"

if [ "${REPLAY_STATUS}" -ne 0 ]; then
    fail_phase replay-analysis "mDNS replay analysis failed"
    echo "mDNS replay analysis failed for ${PCAP_CAPTURE}" >&2
    exit "${REPLAY_STATUS}"
fi

finish_phase replay-analysis "mDNS capture analysis passed"
write_result pass replay-analysis "mDNS capture analysis passed"
echo "=== mDNS harness validation passed ==="
